plugins {
    id 'com.android.application' version '8.7.3'
}

android {
    namespace 'com.dtinh.lichviet'
    compileSdk 34

    defaultConfig {
        applicationId 'com.dtinh.lichviet'
        minSdk 30
        targetSdk 34
        versionCode 43
        versionName '2.2.0'
        multiDexEnabled false
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
        }
        test.java.srcDirs = ['tests']
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            debuggable false
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packaging {
        resources.excludes += ['META-INF/**', '**/*.kotlin_metadata']
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
        warningsAsErrors false
    }
}
